name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build .exe file
        run: |
          pyinstaller --onefile WallpaperDownloader.py
          mkdir dist/exe_output
          mv dist/WallpaperDownloader.exe dist/exe_output/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name windows-exe
          path dist/exe_output

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip fakeroot dpkg-dev
          pip3 install pyinstaller

      - name: Build .deb package
        run: |
          pyinstaller --onefile WallpaperDownloader.py
          mkdir dist/deb_output
          mkdir -p dist/deb_output/usr/local/bin
          cp dist/main dist/deb_output/usr/local/bin/WallpaperDownloader
          mkdir -p dist/deb_output/DEBIAN
          echo "Package: WallpaperDownloader" > dist/deb_output/DEBIAN/control
          echo "Version: 1.0" >> dist/deb_output/DEBIAN/control
          echo "Architecture: all" >> dist/deb_output/DEBIAN/control
          echo "Maintainer: Nicolhetti nicolhetti.pj@gmail.com" >> dist/deb_output/DEBIAN/control
          echo "Description: Este programa en Python con interfaz gráfica (GUI) permite descargar elementos del workshop de Wallpaper Engine." >> dist/deb_output/DEBIAN/control
          dpkg-deb --build dist/deb_output dist/WallpaperDownloader.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name linux-deb
          path dist/WallpaperDownloader.deb

  release:
    needs: [build_windows, build_linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-exe
          path: artifacts/windows

      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: linux-deb
          path: artifacts/linux

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/windows/*.exe
            artifacts/linux/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
