name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build .exe file
        run: |
          pyinstaller --onefile WallpaperDownloader.py
          mkdir dist\package_output
          move dist\WallpaperDownloader.exe dist\package_output\WallpaperDownloader.exe

      - name: Copy DepotDownloaderMod
        run: |
          xcopy "DepotDownloaderMod" "dist\package_output\DepotDownloaderMod" /E /I /Q /Y

      - name: Create ZIP package
        run: |
          powershell Compress-Archive -Path dist\package_output\* -DestinationPath dist\WallpaperEngineDownloader.zip

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-package
          path: dist/WallpaperEngineDownloader.zip

  release:
    needs: [build_windows]
    runs-on: ubuntu-22.04
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-package
          path: artifacts/windows

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/windows/WallpaperEngineDownloader.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
